
ARG FEDORA_VERSION="43"
ARG YKMAN_VERSION="5.8.0"
ARG PCSC_LITE_VERSION="2.4.1"

################################################################################
FROM quay.io/fedora/fedora:${FEDORA_VERSION} as builder

RUN mkdir /builder /scratch

RUN dnf install \
        --assumeyes \
        --setopt=install_weak_deps=False \
        --nodocs \
        cmake \
        doxygen \
        flex \
        gcc \
        meson \
        pod2man \
        polkit-devel \
        python3-devel \
        python3-pip \
        systemd-devel \
        systemd-udev

RUN dnf install \
        --assumeyes \
        --installroot=/scratch \
        --use-host-config \
        --no-docs \
        --setopt=install_weak_deps=False \
        bash \
        python3 && \
    dnf clean all \
        --installroot=/scratch

ARG PCSC_LITE_VERSION
RUN curl -L -#  https://github.com/LudovicRousseau/PCSC/archive/refs/tags/${PCSC_LITE_VERSION}.tar.gz \
    | tar -C /builder -zxv \
    && cd /builder/PCSC-${PCSC_LITE_VERSION} \
    && meson setup --prefix=/usr builddir \
    && meson compile -C builddir pcsclite \
    && meson install -C builddir --destdir=/scratch

RUN  pip install \
        --config-settings="--global-option=build_ext" \
        --config-settings="--global-option=-L/scratch/usr/lib64/" \
        --config-settings="--global-option=-I/scratch/usr/include/PCSC" \
        --root=/scratch \
        --root-user-action=ignore \
        --no-warn-script-location \
        pyscard

ARG YKMAN_VERSION
RUN pip install \
        --root=/scratch \
        --root-user-action=ignore \
        --no-warn-script-location \
        "yubikey-manager==${YKMAN_VERSION}"

RUN useradd \
        --user-group \
        --create-home \
        --shell=/bin/bash \
        --prefix=/scratch \
        ykman

################################################################################

FROM scratch

ARG YKMAN_VERSION
LABEL org.opencontainers.image.authors="W Anders <w@doubleu.codes>"
LABEL org.opencontainers.image.url="https://github.com/doubleu-labs/containers"
LABEL org.opencontainers.image.documentation="https://github.com/doubleu-labs/containers"
LABEL org.opencontainers.image.source="https://github.com/doubleu-labs/containers"
LABEL org.opencontainers.image.vendor="DoubleU Labs"
LABEL org.opencontainers.image.licenses="MIT,BSD-2-Clause"
LABEL org.opencontainers.image.title="DoubleU Labs yubikey-manager (ykman)"
LABEL org.opencontainers.image.description="Manage YubiKey devices from a container."
LABEL com.yubico.yubikey-manager.version="$YKMAN_VERSION"

COPY --from=builder /scratch /

USER ykman

WORKDIR /home/ykman

CMD [ "/bin/bash" ]