---
name: Build CoreDNS
on:
  push:
    paths:
    - 'coredns/*'
    - '!coredns/README.md'
  workflow_dispatch:
env:
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ env.PLATFORMS }}
    - uses: docker/setup-buildx-action@v3
      id: buildx
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}
    - uses: docker/build-push-action@v5
      with:
        builder: ${{ steps.buildx.outputs.name }}
        file: coredns/Containerfile
        platforms: ${{ env.PLATFORMS }}
        push: true
        tags: |
          ghcr.io/doubleu-labs/coredns:latest
          quay.io/doubleu-labs/coredns:latest
