---
name: Build dnsmasq
on:
  push:
    paths:
    - 'dnsmasq/*'
    - '!dnsmasq/README.md'
  workflow_dispatch:
env:
  PLATFORMS: linux/amd64,linux/arm64
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: get-tags
      run: |
        VERSION=$(cat dnsmasq/VERSION)
        TAGS=(
          "ghcr.io/doubleu-labs/dnsmasq:latest"
          "ghcr.io/doubleu-labs/dnsmasq:${VERSION}"
          "quay.io/doubleu-labs/dnsmasq:latest"
          "quay.io/doubleu-labs/dnsmasq:${VERSION}"
        )
        TAGSCSV=$(printf '%s,' "${TAGS[@]}")
        echo "tags=${TAGSCSV:0:-1}" >> $GITHUB_OUTPUT
    - id: get-nortctags
      run: |
        VERSION=$(cat dnsmasq/VERSION)
        TAGS=(
          "ghcr.io/doubleu-labs/dnsmasq-nortc:latest"
          "ghcr.io/doubleu-labs/dnsmasq-nortc:${VERSION}"
          "quay.io/doubleu-labs/dnsmasq-nortc:latest"
          "quay.io/doubleu-labs/dnsmasq-nortc:${VERSION}"
        )
        TAGSCSV=$(printf '%s,' "${TAGS[@]}")
        echo "tags=${TAGSCSV:0:-1}" >> $GITHUB_OUTPUT
    - uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ env.PLATFORMS }}
    - uses: docker/setup-buildx-action@v3
      id: buildx
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}
    - uses: docker/build-push-action@v6
      with:
        builder: ${{ steps.buildx.outputs.name }}
        file: dnsmasq/Containerfile
        platforms: ${{ env.PLATFORMS }}
        push: true
        tags: ${{ steps.get-tags.outputs.tags }}
    - uses: docker/build-push-action@v6
      with:
        builder: ${{ steps.buildx.outputs.name }}
        file: dnsmasq/Containerfile
        build-args: |
          IMG_TITLE="dnsmasq-nortc"
          BUILD_COPTS="-DHAVE_BROKEN_RTC"
        platforms: ${{ env.PLATFORMS }}
        push: true
        tags: ${{ steps.get-nortctags.outputs.tags }}
