---
name: Build Netbox
on:
  push:
    paths:
    - 'netbox/*'
    - '!netbox/README.md'
  workflow_dispatch:
env:
  CONTAINER: netbox

################################################################################

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - arch: linux/amd64
            runner: ubuntu-24.04
          - arch: linux/arm64
            runner: ubuntu-24.04-arm
    name: Build Container (${{ matrix.target.arch }})
    runs-on: ${{ matrix.target.runner }}
    steps:
    #===========================================================================
    - name: Checkout
      uses: actions/checkout@v4
    #===========================================================================
    - name: Prepare Platform
      id: platform
      run: |
        platform=${{ matrix.target.arch }}
        echo "platform=${platform//\//-}" >> $GITHUB_OUTPUT
    #===========================================================================
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    #===========================================================================
    - name: Login to Quay
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}
    #===========================================================================
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    #===========================================================================
    - name: Build and Push by Digest
      id: build
      uses: docker/build-push-action@v6
      with:
        platforms: ${{ matrix.target.arch }}
        file: ${{ env.CONTAINER }}/Containerfile
        context: ${{ env.CONTAINER }}/
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ env.CONTAINER }}
          quay.io/${{ github.repository_owner }}/${{ env.CONTAINER }}
        outputs: type=image,push-by-digest=true,name-canonical=true,push=true
    #===========================================================================
    - name: Export Digest
      run: |
        mkdir -p ${{ runner.temp }}/digests
        digest="${{ steps.build.outputs.digest }}"
        touch "${{ runner.temp }}/digests/${digest#sha256:}"
    #===========================================================================
    - name: Upload Digest
      uses: actions/upload-artifact@v4
      with:
        name: digests-${{ steps.platform.outputs.platform }}
        path: ${{ runner.temp }}/digests/*
        if-no-files-found: error
        retention-days: 1

################################################################################

  merge_platform_containers:
    name: Merge Platform Containers
    runs-on: ubuntu-latest
    needs: build
    steps:
    #===========================================================================
    - name: Checkout
      uses: actions/checkout@v4
    #===========================================================================
    - name: Get Version from File
      id: version
      run: echo "version=$(cat ${{ env.CONTAINER }}/VERSION)" >> $GITHUB_OUTPUT
    #===========================================================================
    - name: Download Digests
      uses: actions/download-artifact@v4
      with:
        path: ${{ runner.temp }}/digests
        pattern: digests-*
        merge-multiple: true
    #===========================================================================
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    #===========================================================================
    - name: Login to Quay
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}
    #===========================================================================
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    #===========================================================================
    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/${{ env.CONTAINER }}
          quay.io/${{ github.repository_owner }}/${{ env.CONTAINER }}
        tags: |
          type=raw,latest
          type=raw,${{ steps.version.outputs.version }}
    #===========================================================================
    - name: Create Manifest List and Push
      working-directory: ${{ runner.temp }}/digests
      run: |
        docker buildx imagetools create \
          $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
          $(printf 'ghcr.io/${{ github.repository_owner }}/${{ env.CONTAINER }}@sha256:%s ' *) \
          $(printf 'quay.io/${{ github.repository_owner }}/${{ env.CONTAINER }}@sha256:%s ' *) \
